### ISSUE TITLE
bug in `triton_instr` macro: call

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#247] opened 2024-01-19 14:10 UTC
From what it looks like, the `triton_instr` macro when used to create a `call` instruction, does not take the *value* of the variable of type `String` but its *name*.

For instance, the following snippet results, down the line, in an error because the VM cannot find the label "entrypoint":
```rust
        let entrypoint = fri_verify.entrypoint();
        invocation_code.push(triton_instr!(call entrypoint));
```

I think (but I'm not 100% sure) the problem comes from lines 456-460 in `lib.rs`:
```rust
    (call $arg:ident) => {{
        let argument = stringify!($arg).to_string();
        let instruction = $crate::instruction::AnInstruction::<String>::Call(argument);
        $crate::instruction::LabelledInstruction::Instruction(instruction)
    }};
```

My understanding of `stringify` is that it takes that it takes whatever expression was supplied and turns it into a string -- not whatever the expression evaluates to at runtime. For instance, the following code outputs "msg" rather than "Hi!":
```rust
fn main() {
    let msg = "Hi!";
    println!(stringify!(msg));
}
```

So even though the macro guards against using `call` with anything *but* a variable or function name, you still end up with a call instruction that jumps to the identifier not to the value of the variable.

Please take this bug analysis with a grain of salt; I'm not as well-versed with rust macros as I would like to be.

If this analysis is correct and the macro needs to be fixed (and not my understanding and use of it) then I would suggest fixing it in a way that allows expressions as arguments, so that `triton_instr!(call fri_verify.entrypoint())` is valid.

**Comment by jan-ferdinand** [comment] 2024-01-19 14:18
I think this is related to #243. The current workaround is to rely on `triton_asm!`, even though that might lead to uglier code – sorry. :bow The long-term goal is to re-write all macros such that they are procedural, also eliminating the need to increase the recursion depth.

**Comment by jan-ferdinand** [comment] 2024-05-11 20:22
The underlying issue is a duplicate of #243, although the symptom you describe here is not. Planned in a future refactor.

**Closed by jan-ferdinand** 2024-05-11 20:22 UTC
Labels: 📋 duplicate
